name: Mirror

on: [push, delete]

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: git-sync
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:jeffmccormick/nlog-cassandra.git"
          source_branch: "*"
          source_ssh_private_key: ${{ secrets.REPO_PRIVATE_KEY }}
          destination_repo: "https://oauth2:${{ secrets.GITLAB_ACCESS_TOKEN }}@git.dmcinfo.com/jeffreym/mirror-test.git"
          destination_branch: "*"
